# Contains the DAG (more like ROSE structure) connecting the tasks together.
#
# What should **not** be here: parsing the resources / tasks directories. This
# is for the utils_architecture.py


#
# # Example standalone implementation of RBF surrogate modeling from xGFabric project.
#
# Basic sequential learner.
#
# 1. Gather raw input data.
# 2. Generate simulations given input data
# 3. Train three models (in parallel)
# 4. Evaluate against separate dataset. Pick top 5 worst points and add to
#    dataset.
# 5. Repeat.
#
# ---
#
# Example data:
# `$SCRATCH/playground/raw_data/sensor_out.csv` <-- obtained by `~/xgfabric/ryan_repo/demo2/nd/CFDaAI/utils/get_data.sh`
#
# Simulation data:
# `$SCRATCH/playground/simulations/<WIND_VECTOR>.csv` <-- generated by simulation step
#
# Train models:
# `$SCRATCH/playground/models/<MODEL>.tar.gz` <-- generated by model step
#
# Evaluation data:
# Random values for now.

# Env must be first
import glob
from pathlib import Path

from dotenv import load_dotenv

from reports.plot_workflow_dashboard import plot_split
from reports.plot_workflow_gantt import plot as plot_gantt

from tasks.common.log_formatter import register_log_main

load_dotenv("tasks/common/config.sh")
import rhapsody
import logging

rhapsody.enable_logging(
    level=logging.INFO,
)

import asyncio
import os
from radical.asyncflow import WorkflowEngine
import logging
from rose.al.active_learner import Learner

from utils_architecture import verify_config, get_fdate

# Load backends:
from resources.local_cpu import LocalCPU
from resources.nersc_cpu import NerscCPU
from resources.nersc_gpu import NerscGPU

# Tasks:
from tasks.get_data import tk_get_data
from tasks.do_simulation import tk_do_simulation
from tasks.do_pcr import tk_do_pcr, tk_pcr_partition, tk_do_pcr_pack
from tasks.do_pinn import tk_do_pinn
from tasks.do_fno import tk_do_fno
from tasks.to_edge import tk_to_edge

verify_config()

# Telemetry must be disabled for LocalCPU backend
ENABLE_TELEMETRY = True
NODE_COUNT = 18
CONCURRENCY_LIMIT = 72


async def main():
    # Setup environment
    # Create interim directory for storing logs / outputs
    dt_str = get_fdate()
    os.makedirs(os.getenv("PLAYGROUND_DIR") + f"/run_{dt_str}")
    os.environ["PLAYGROUND_DIR"] = os.getenv("PLAYGROUND_DIR") + f"/run_{dt_str}"

    # Get backends
    nersc_cpu = NerscCPU(node_count=NODE_COUNT)
    backend_nersc_cpu = await nersc_cpu.get_backend()
    asyncflow = await WorkflowEngine.create(
        backend=[backend_nersc_cpu],
    )

    if ENABLE_TELEMETRY:
        telemetry = await asyncflow.start_telemetry(
            resource_poll_interval=0.5,
            checkpoint_path=os.getenv("PLAYGROUND_DIR") + "/telemetry",
        )

    logger = register_log_main(
        os.getenv("PLAYGROUND_DIR") + "/rose.log",
        os.getenv("PLAYGROUND_DIR") + "/libs.log",
        logging.INFO,
    )

    # Setup environment
    logging.getLogger("matplotlib.font_manager").setLevel(logging.INFO)
    logging.getLogger("matplotlib.colorbar").setLevel(logging.INFO)

    logger.info("Warming up post engine creation....")

    # Define ROSE APP style
    acl = Learner(asyncflow)

    # Define tasks
    get_data = acl.utility_task(as_executable=False)(tk_get_data)

    do_sim = acl.simulation_task(as_executable=False)(tk_do_simulation)

    do_pinn = acl.training_task(as_executable=False)(tk_do_pinn)
    do_fno = acl.training_task(as_executable=False)(tk_do_fno)

    do_pcr_partition = acl.utility_task(as_executable=False)(tk_pcr_partition)
    do_pcr = acl.training_task(as_executable=False)(tk_do_pcr)
    do_pcr_pack = acl.utility_task(as_executable=False)(tk_do_pcr_pack)

    to_edge = acl.training_task(as_executable=False)(tk_to_edge)

    # Create pipeline
    async def pipeline(pipeline_id):
        async with asyncflow.workflow_scope(1):
            # if True:
            logger.info("Start pipeline!")

            # Create directory to store logs and results
            pipeline_playground = f"{os.getenv('PLAYGROUND_DIR')}/{pipeline_id}"
            os.makedirs(pipeline_playground)
            config = {"PIPELINE_DIR": pipeline_playground}

            sensor_data = await get_data(config.copy())
            # sensor_data spits out 72 points. Run one sim per point.

            sim_jobs = []
            sims = []
            counter = 0
            policies = nersc_cpu.create_cpu_policies(policy_count=CONCURRENCY_LIMIT)
            for policy in policies:
                logger.debug(f"Policy: {policy}")
            for i, data_point in enumerate(sensor_data):
                sim_jobs.append(
                    do_sim(
                        config.copy(),
                        data_point,
                        i,
                        # task_description={
                        #     "process_template": {"policy": policies[i % len(policies)]}
                        # },
                    )
                )
                counter += 1
                if counter == CONCURRENCY_LIMIT:
                    logger.info(f"Awaiting based on concurrency limit")
                    sims += await asyncio.gather(*sim_jobs)
                    logger.debug(f"Sims: {sims}")
                    sim_jobs = []
                    counter = 0

            logger.debug(f"Awaiting remaining {sim_jobs}")
            sims += await asyncio.gather(*sim_jobs)

            # barrier. Wait for all sims to complete

            sim_ids = ""
            data_list = []
            for sim_id, wind_speed, sim_csv in sims:
                sim_ids = str(sim_id) + ","
                data_list.append((wind_speed, sim_csv))

            sim_ids = sim_ids[:-1]

            # now, train using the results form the sims
            # then push to edge when complete

            t_policy = nersc_cpu.create_cpu_policies(
                policy_count=CONCURRENCY_LIMIT, core_count=128
            )
            for policy in policies:
                logger.debug(f"Training Policy: {policy}")

            train_jobs = [
                to_edge(
                    config.copy(),
                    do_fno(
                        config.copy(),
                        data_list,
                        # task_description={
                        #     "process_template": {"policy": t_policy[0 % len(t_policy)]}
                        # },
                    ),
                    "fno",
                ),
                to_edge(
                    config.copy(),
                    do_pinn(
                        config.copy(),
                        data_list,
                        # task_description={
                        #     "process_template": {"policy": t_policy[0 % len(t_policy)]}
                        # },
                    ),
                    "pinn",
                ),
            ]

            @asyncflow.block
            async def pcr_block(config, data_list, sensor_data):
                # do this independently of the workflow

                pcr_policy = nersc_cpu.create_cpu_policies(
                    policy_count=int(os.getenv("PCR_MACHINE_SPLITS")), core_count=2
                )

                partitions = await do_pcr_partition(
                    config.copy(),
                    data_list,
                    sensor_data,
                )
                pcr_jobs = []
                for i, partition in enumerate(partitions):
                    pcr_jobs.append(
                        do_pcr(
                            config.copy(),
                            partition,
                            # task_description={
                            #     "process_template": {"policy": pcr_policy[i]}
                            # },
                        )
                    )
                return await to_edge(
                    config.copy(), do_pcr_pack(config.copy(), *pcr_jobs), "pcr"
                )

            train_jobs.append(pcr_block(config, data_list, sensor_data))

            edge_result = await asyncio.gather(*train_jobs)

            logger.info(f"Pipeline completed: {edge_result}")

    results = await pipeline(1)

    await asyncio.sleep(1)
    logger.info(f"Program complete! Results: {results}")

    logger.info(f"Telemetry summary: {telemetry.summary()}")
    await acl.shutdown()
    if ENABLE_TELEMETRY:
        await telemetry.stop()

        # Call reports
        for f in glob.glob(
            os.getenv("PLAYGROUND_DIR") + "/telemetry/*.telemetry.jsonl"
        ):
            plot_split(f)

        for f in glob.glob(
            os.getenv("PLAYGROUND_DIR") + "/telemetry/*.telemetry.jsonl"
        ):
            plot_gantt(Path(f))


if __name__ == "__main__":
    asyncio.run(main())
