# Contains the DAG (more like ROSE structure) connecting the tasks together.
#
# What should **not** be here: parsing the resources / tasks directories. This
# is for the utils_architecture.py


#
# # Example standalone implementation of RBF surrogate modeling from xGFabric project.
#
# Basic sequential learner.
#
# 1. Gather raw input data.
# 2. Generate simulations given input data
# 3. Train three models (in parallel)
# 4. Evaluate against separate dataset. Pick top 5 worst points and add to
#    dataset.
# 5. Repeat.
#
# ---
#
# Example data:
# `$SCRATCH/playground/raw_data/sensor_out.csv` <-- obtained by `~/xgfabric/ryan_repo/demo2/nd/CFDaAI/utils/get_data.sh`
#
# Simulation data:
# `$SCRATCH/playground/simulations/<WIND_VECTOR>.csv` <-- generated by simulation step
#
# Train models:
# `$SCRATCH/playground/models/<MODEL>.tar.gz` <-- generated by model step
#
# Evaluation data:
# Random values for now.

# Env must be first
from dotenv import load_dotenv

load_dotenv("tasks/common/config.sh")

import asyncio
import os
from radical.asyncflow import WorkflowEngine
from radical.asyncflow.logging import init_default_logger
import logging
from rose.al.active_learner import Learner

from utils_architecture import verify_config, get_fdate

# Load backends:
from resources.local_cpu import LocalCPU as LocalCPU

# Tasks:
from tasks.get_data import tk_get_data
from tasks.do_simulation import tk_do_simulation
from tasks.do_pcr import tk_do_pcr, tk_pcr_partition, tk_do_pcr_pack
from tasks.do_pinn import tk_do_pinn
from tasks.do_fno import tk_do_fno
from tasks.to_edge import tk_to_edge

logger = logging.getLogger(__name__)


verify_config()


async def main():
    # Setup environment
    init_default_logger(logging.INFO)

    logger.info("Warming up....")

    # Create interim directory for storing logs / outputs
    dt_str = get_fdate()
    os.makedirs(os.getenv("PLAYGROUND_DIR") + f"/run_{dt_str}")
    os.environ["PLAYGROUND_DIR"] = os.getenv("PLAYGROUND_DIR") + f"/run_{dt_str}"

    # Get backends
    local_cpu = LocalCPU()
    backend_local_cpu = await local_cpu.get_backend()
    asyncflow = await WorkflowEngine.create(
        backend=[backend_local_cpu],
    )

    # Define ROSE APP style
    acl = Learner(asyncflow)

    # Define tasks
    get_data = acl.utility_task(as_executable=False)(tk_get_data)

    do_sim = acl.simulation_task(as_executable=False)(tk_do_simulation)

    do_pinn = acl.training_task(as_executable=False)(tk_do_pinn)
    do_fno = acl.training_task(as_executable=False)(tk_do_fno)

    do_pcr_partition = acl.utility_task(as_executable=False)(tk_pcr_partition)
    do_pcr = acl.training_task(as_executable=False)(tk_do_pcr)
    do_pcr_pack = acl.utility_task(as_executable=False)(tk_do_pcr_pack)

    to_edge = acl.training_task(as_executable=False)(tk_to_edge)

    # Create pipeline
    async def pipeline(pipeline_id):
        logger.info("Start pipeline!")

        # Create directory to store logs and results
        pipeline_playground = f"{os.getenv('PLAYGROUND_DIR')}/{pipeline_id}"
        os.makedirs(pipeline_playground)
        config = {
            "PIPELINE_DIR": pipeline_playground,
        }

        sensor_data = await get_data(config.copy())
        # sensor_data spits out 72 points. Run one sim per point.

        sim_jobs = []
        for i, data_point in enumerate(sensor_data):
            sim_jobs.append(do_sim(config.copy(), data_point, i))

        # barrier. Wait for all sims to complete
        sims = await asyncio.gather(*sim_jobs)
        sim_ids = ""
        data_list = []
        for sim_id, wind_speed, sim_csv in sims:
            sim_ids = str(sim_id) + ","
            data_list.append((wind_speed, sim_csv))

        sim_ids = sim_ids[:-1]
        config["PARENT_UNIQUE_ID"] = sim_ids

        # now, train using the results form the sims
        # then push to edge when complete

        train_jobs = [
            to_edge(config.copy(), do_fno(config.copy(), data_list), "fno"),
            to_edge(config.copy(), do_pinn(config.copy(), data_list), "pinn"),
        ]

        # add pcr, which has a utility task
        env, partitions = await do_pcr_partition(config.copy(), data_list, sensor_data)

        pcr_jobs = []
        for partition in partitions:
            pcr_jobs.append(do_pcr(env, partition))

        train_jobs.append(to_edge(config.copy(), do_pcr_pack(env, *pcr_jobs), "pcr"))

        edge_result = await asyncio.gather(*train_jobs)

        logger.info(f"Pipeline completed {edge_result}")

    results = await pipeline(1)
    logger.info(f"Program complete! Results: {results}")


if __name__ == "__main__":
    asyncio.run(main())
