name: cspot
channels:
 - conda-forge
dependencies:
 - python=3.10
 - gcc_linux-64
 - gxx_linux-64
 - sysroot_linux-64
 - cmake=3.19.1
 - ninja=1.10.2
 - unzip
 - wget
 - zeromq
 - libmicrohttpd
 - libpcap
 - pkgconfig
 - lz4
 - libcurl
 - libsystemd
 - nss
 - openssl
 - libopenssl-static 
