name: cfdaai
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.12
 - cmake
 - gcc_linux-64
 - gxx_linux-64
 - gnuplot
 - imagemagick
 - h5py
 - libcurl
 - ninja
 - numpy
 - openssl
 - pandas
 - pillow
 - unzip
 - wget
 - yaml
 - zeromq
 - scikit-learn
 - matplotlib
 - jupyter
 - ipykernel
 - ndcctools
 - pip
 - pip:
   - meshio
   - tensorflow
   - keras
   - tqdm
   - numpy
