#
# # Example standalone implementation of RBF surrogate modeling from xGFabric project.
#
# Basic sequential learner.
#
# 1. Gather raw input data.
# 2. Generate simulations given input data
# 3. Train three models (in parallel)
# 4. Evaluate against separate dataset. Pick top 5 worst points and add to
#    dataset.
# 5. Repeat.
#
# ---
#
# Example data:
# `$SCRATCH/playground/raw_data/sensor_out.csv` <-- obtained by `~/xgfabric/ryan_repo/demo2/nd/CFDaAI/utils/get_data.sh`
#
# Simulation data:
# `$SCRATCH/playground/simulations/<WIND_VECTOR>.csv` <-- generated by simulation step
#
# Train models:
# `$SCRATCH/playground/models/<MODEL>.tar.gz` <-- generated by model step
#
# Evaluation data:
# Random values for now.

#
print("Top of cell")
import os
import sys
import time
import asyncio
import logging

# learner and task level imports
import numpy as np

print("Task level imports done")

# ROSE top layer imports
from rose.metrics import MEAN_SQUARED_ERROR_MSE

print("Top layer imports done")

# ROSE Bottom layers imports
from radical.asyncflow import WorkflowEngine

print("Start import of execution backend")
from rhapsody.backends import ConcurrentExecutionBackend, DragonExecutionBackendV3
from concurrent.futures import ProcessPoolExecutor

print("Stop import of execution backend")
from radical.asyncflow.logging import init_default_logger
from rose.al.active_learner import Learner

print("Bottom Layer imports done")

logger = logging.getLogger(__name__)

import csv
import multiprocessing as mp
import pathlib
import json
import glob

# mp.set_start_method("dragon")


async def main():
    init_default_logger(logging.INFO)
    engine = await ConcurrentExecutionBackend(ProcessPoolExecutor())
    # engine = await DragonExecutionBackendV3()

    asyncflow = await WorkflowEngine.create(engine)
    custom_acl = Learner(asyncflow)

    def fetch_simulation_inputs():
        # call the actual script here that fetches sensor inputs.
        sensor_path = "/pscratch/sd/b/bcarter/playground/raw_data/sensor_out.csv"
        out = []
        with open(sensor_path, "r") as f:
            # trim off first line and then split
            reader = csv.DictReader(f)
            out = list(reader)

        sensor_path = "/pscratch/sd/b/bcarter/playground/active_learn/additional.csv"
        if os.path.isfile(sensor_path):
            out2 = []
            with open(sensor_path, "r") as f:
                # trim off first line and then split
                reader = csv.DictReader(f)
                out2 = list(reader)
            out = out + out2

        # print(out)
        return out

    # ========================================================================
    # 1. SETUP TASK
    # ========================================================================
    @custom_acl.utility_task(as_executable=False)
    async def setup(*args, **kwargs) -> list:
        logger.info("=== SETUP: Generating data ===")
        print("Setup")
        input_wind_speeds = fetch_simulation_inputs()[0:10]

        # create working folder.
        # os.makedirs("/pscratch/sd/b/bcarter/playground/working",exist_ok=True)
        # out_dir = pathlib.Path("/pscratch/sd/b/bcarter/playground/working")

        # Now, convert to sim params
        out = []
        for idx, wind_record in enumerate(input_wind_speeds):
            out.append(
                {
                    "sim_id": str(idx),
                    "wind_speed": wind_record["windspeed_ms"],
                    "wind_direction": wind_record["winddir"],
                }
            )
        return out

    # ========================================================================
    # 1. SIMULATION TASK
    # ========================================================================

    @custom_acl.simulation_task(as_executable=False)
    async def simulation(*args, **kwargs) -> dict:
        simulation_params = args[0]
        logger.info(
            f"=== SIMULATION: Generating simulation for point {simulation_params['wind_speed']} and {simulation_params['wind_direction']} ==="
        )
        # Now, do the simulation.
        time.sleep(30)  # it takes time
        logger.info(f"=== SIMULATION: Done. Saving...")

        # generate some randomness.
        # 11 x 1000 rows
        # x,y,z,p,nut,k,epsilon,U_0,U_1,U_2,U_Magnitude
        sim_data = np.random.random(size=(1000, 11))
        headers = "x,y,z,p,nut,k,epsilon,U_0,U_1,U_2,U_Magnitude"

        filename_safe = f"fake_sim_{simulation_params['wind_speed'].replace('.','_')}_{simulation_params['wind_direction'].replace('.','_')}.csv"
        np.savetxt(
            "/pscratch/sd/b/bcarter/playground/simulations/" + filename_safe,
            sim_data,
            delimiter=",",
            header=headers,
            comments="",  # prevents '#' from being added before the header
        )
        return filename_safe

    def do_pcr(sims):
        os.makedirs("/pscratch/sd/b/bcarter/playground/models", exist_ok=True)
        with open("/pscratch/sd/b/bcarter/playground/models/pcr.model", "w") as f:
            f.write("Hello!\n")
            for sim in sims:
                f.write(sim)
                f.write("\n")

        return "/pscratch/sd/b/bcarter/playground/models/pcr.model"

    def do_pinn(sims):
        os.makedirs("/pscratch/sd/b/bcarter/playground/models", exist_ok=True)
        time.sleep(20)
        with open("/pscratch/sd/b/bcarter/playground/models/pinn.model", "w") as f:
            f.write("Hello!\n")
            for sim in sims:
                f.write(sim)
                f.write("\n")

        return "/pscratch/sd/b/bcarter/playground/models/pinn.model"

    def do_fno(sims):
        os.makedirs("/pscratch/sd/b/bcarter/playground/models", exist_ok=True)
        time.sleep(20)
        with open("/pscratch/sd/b/bcarter/playground/models/fno.model", "w") as f:
            f.write("Hello!\n")
            for sim in sims:
                f.write(sim)
                f.write("\n")

        return "/pscratch/sd/b/bcarter/playground/models/fno.model"

    @custom_acl.training_task(as_executable=False)
    async def training(*args, **kwargs) -> dict:
        training_sims = args[0]
        training_mode = args[1]

        all_sims = glob.glob("/pscratch/sd/b/bcarter/playground/simulations/*.csv")

        # TODO: Later, implement synchronization and barriers...

        logger.info(f"=== TRAINING: Generating {training_mode} model ===")

        if training_mode == "pcr":
            out = do_pcr(all_sims)

        elif training_mode == "pinn":
            out = do_pinn(all_sims)

        elif training_mode == "fno":
            out = do_fno(all_sims)

        logger.info(f"=== TRAINING: Done generating {training_mode} model ===")
        return out

    # ========================================================================
    # 3. ACTIVE LEARNING TASK
    # ========================================================================
    @custom_acl.active_learn_task(as_executable=False)
    async def active_learn(*args, **kwargs) -> dict:
        training_models = args

        resample = []
        for model in training_models:
            logger.info(
                f"=== ACTIVE LEARNING: Selecting samples for model: {model} ==="
            )
            samples = np.random.random((100, 2))

            for sample in samples[2:6]:
                resample.append({"windspeed_ms": sample[0], "winddir": sample[1]})

        time.sleep(4)

        # calculate worst numbers
        # send numbers to sim.
        sensor_path = "/pscratch/sd/b/bcarter/playground/active_learn/additional.csv"
        with open(sensor_path, "w") as f:
            #
            f.write("dt,windspeed_ms,windavg_ms,winddir\n")
            for item in resample:
                f.write(
                    f"0000-00-00T00:00:00.000000,{item['windspeed_ms']},{item['windspeed_ms']},{item['winddir']}\n"
                )

        return resample

    # #### But what if I want to stop the execution earlier if my performance metric is reached?

    # @acl.as_stop_criterion(metric_name=MEAN_SQUARED_ERROR_MSE, threshold=0.1, as_executable=False)
    # async def check_mse():
    #     """
    #     Your stop condition
    #     1-For each AL iteration, check if MSE <= 0.1
    #     2-Terminate early if reached
    #     """

    # MAIN

    async def start():
        # 10 iterations of active learning
        for acl_iter in range(1):
            logger.info(f"=== ITERATION START {acl_iter} ===")

            # SETUP.
            sim_params = await setup()

            simulation_jobs = []

            for sim in sim_params:
                simulation_jobs.append(simulation(sim))

            # barrier
            sims = await asyncio.gather(*simulation_jobs)

            # now, for training
            training_jobs = []
            for mode in ["fno", "pinn", "pcr"]:
                training_jobs.append(training(sims, mode))

            # Then, do active learn
            result = await active_learn(*training_jobs)

    # engine = await DragonExecutionBackendV3(num_nodes=2)
    logger.info("Starting simple RBF active learning with ROSE...")

    # invoke the custom/user-defined start() method
    # I only want one parallel runner.
    results = await asyncio.gather(*[start()])

    logger.info("Active Learning completed!")


if __name__ == "__main__":
    asyncio.run(main())
